---
apiVersion: v1
kind: Namespace
metadata:
  name: consumer
  labels:
    app.kubernetes.io/component: dataspace-participant
    app.kubernetes.io/part-of: mvd
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
---
apiVersion: v1
kind: Namespace
metadata:
  name: provider
  labels:
    app.kubernetes.io/component: dataspace-participant
    app.kubernetes.io/part-of: mvd
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
---
apiVersion: v1
kind: Namespace
metadata:
  name: dataspace-issuer
  labels:
    app.kubernetes.io/component: credential-issuer
    app.kubernetes.io/part-of: mvd
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
